apiVersion: "v1"
kind: "PersistentVolume"
metadata:
  name: "metrics-cassandra-1"
  labels:
    storage-name: "metrics-cassandra-1"
spec:
  capacity:
    storage: "10Gi"
  accessModes:
    - "ReadWriteOnce"
  nfs:
    path: "/exports/metrics/"
    server: "yzamir-centos7-1.eng.lab.tlv.redhat.com"
  persistentVolumeReclaimPolicy: "Retain"
